# .sops.yaml - SOPS 配置文件
#
# 使用方法:
# 1. 从 SSH 密钥生成 age 密钥:
#    ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
#    ssh-to-age < ~/.ssh/id_ed25519.pub
#
# 2. 创建/编辑 secrets:
#    sops secrets/secrets.yaml
#
# 3. 查看 secrets:
#    sops -d secrets/secrets.yaml

keys:
    - &wslrsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaKzP+PbGAhundgHlKsJ75420SAfXCGQdEUA8XWBU7mUV+aoXYSiYy8eAf0thrNF61hojw6WZ4agIRIM4bF2gH75Kjc2v4jwPNsVtC9VAQM6WXoikmpSFWDRL7R0T//Y7eQRP/sfPH4jGedakeHqucp3DKn1Vw6KnsgpLWfgY6MEQDgplj33JyiR3gYpiGVT082nGMOHSWqIf5cpkHFNa9zF0Nae3U3MNwoFyYtNjWxj/lGnn4AU6gdSW40UiBs6e2T2Lhb0tT2EANRab8p3r2X5EIMTeGCIr2yyhmBbILhGnkYI80sXMq53sXHrnteWnxnhpXTZ4UpHBUp+Ab2yk7ZmZU7671YiIe50UzbH3GR1JFLclvOJvxiOvTfCA3o15VSNGFKehwVBR0EoOiLY3nmBzrZNZ0tRDR/CeBePLU3HsPWPPeZmmGEUj1fO8CsHTHL9JdqFhV94IY5+yfycR7EHNEFh66SprV0n0YoHOUogyBjrUclUTcGef4yfe0XR0= VitusWsl
    # ========== WSL ==========
    - &wsl age1pmpct65e9p6xymw0fxs8zed7t9wkmku9k74pxqjevwnv5yvhxqlqrwsnku
    - &vitus8500 age1paytx9hm9c475yd4fywuqa9mm0zcm5ekg07l0wjkjyjnakxxqudseny95h
    - &vitus5600 age1rpxxn0dpeda320mxsgyzrswv754tguz3h8m0p9s8sd5wxup9f9us7p28xq
    # ========== Darwin (macOS) ==========
    - &vitusmac age12l22pkwhea5pa5ske2ejckpg44qwu8wgv2u98a0zs0ne6m90nucsvr5qm6 # TODO: 在 Mac 上运行 ssh-to-age < ~/.ssh/id_ed25519.pub 获取

creation_rules:
    # 所有 secrets 文件的加密规则
    - path_regex: secrets/.*
      key_groups:
          - age:
                - *wslrsa
                - *wsl
                - *vitusmac
                - *vitus8500
                - *vitus5600