# .sops.yaml - SOPS 配置文件
#
# 使用方法:
# 1. 从 SSH 密钥生成 age 密钥:
#    ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
#    ssh-to-age < ~/.ssh/id_ed25519.pub
#
# 2. 创建/编辑 secrets:
#    sops secrets/secrets.yaml
#
# 3. 查看 secrets:
#    sops -d secrets/secrets.yaml

keys:
  # ========== NixOS 主机 ==========
  - &vitus5600 age1xxxxxxxxxx  # TODO: 运行 ssh-to-age < ~/.ssh/id_ed25519.pub 获取
  - &vitus8500 age1xxxxxxxxxx  # TODO: 运行 ssh-to-age < ~/.ssh/id_ed25519.pub 获取

  # ========== WSL ==========
  - &wsl age1pmpct65e9p6xymw0fxs8zed7t9wkmku9k74pxqjevwnv5yvhxqlqrwsnku

  # ========== Darwin (macOS) ==========
  - &vitusmac age1xxxxxxxxxx  # TODO: 在 Mac 上运行 ssh-to-age < ~/.ssh/id_ed25519.pub 获取

creation_rules:
  # 所有 secrets 文件的加密规则
  - path_regex: secrets/.*
    key_groups:
      - age:
          - *vitus5600
          - *vitus8500
          - *wsl
          - *vitusmac
